Cleanup of user_input and runtime store
intechstudio/grid-editor pull request #545
Opened 2024-01-04 18:09 UTC by elsoazemelet

Closes #538 

The cleanup affected almost if not all functionality of grid editor.

**These changes (not exclusively) include the following:**

- Additional various fixes were included when user_input was reworked into a clean, mostly readonly object.
- Additional functional reworks were included when the necessary user_input "pinging" (e.g.: user_input.update((n) => n)) was reduced into a new Promise based functionality.
- Parts of unnecessary complex code were removed, and/or was recreated in a semantically equivalent way. 

**Consequences:**

The base functionalities of editor are working as expected, the editor seems to be working as expected. 
However, since the risk of introduced bugs are high, thorough testing might be necessary before release.

2024-01-04 22:41 UTC, SukuWc requested changes
Changes are on track, please fix minor code style issues based on my comments!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/grid-layout/grid-modules/Device.svelte
Could possibly cause 'Cannot read properties of undefined' ha device undefined!

Consider using device?.dx and device?.dy

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/panels/configuration/components/Pages.svelte
If $user input is never undefined then no need to use try ... catch!

If $user_input can be undefined (which it should not) then use ?. operator!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/grid-layout/grid-modules/overlays/PresetLoadOverlay.svelte
> +  function handleDeviceChange(rt) {
parameter rt is misleading and unused. Give it proper name and use it instead of using device global variable directly!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/grid-layout/grid-modules/overlays/PresetLoadOverlay.svelte
> +    try {
please use guard clauses or ?. operator instead of try ... catch

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/grid-layout/grid-modules/underlays/ActiveChanges.svelte
> +    try {
Eliminate try ... catch using proper conditional statements. This will greatly improve readability of the code!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/panels/configuration/ElementSelectionPanel.svelte
>      } else {
else creates unnecessary indentation after guard clause

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/user-interface/ActiveChanges.svelte
Good use of promises, nice!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/runtime/runtime.store.js
Brave changes, but looks good. Needs testing effort to verify!

2024-01-04 22:41 UTC, SukuWc commented on src/renderer/main/panels/profileCloud/ProfileCloud.svelte
use const ui instead of const li

2024-01-05 22:36 UTC, SukuWc reviewed
Updates look good, still waiting for feedback from QA regarding stability!

2024-01-05 22:37 UTC, SukuWc commented on src/renderer/main/grid-layout/grid-modules/overlays/PresetLoadOverlay.svelte
> +  function handleDeviceChange(rt) {
@elsoazemelet please check this!

2024-01-05 22:44 UTC, SukuWc reviewed
Mostly ok, please check comments!

2024-01-05 22:44 UTC, SukuWc commented on src/renderer/main/panels/configuration/ElementSelectionPanel.svelte
>    function handleSelectionChange(value) {
value is very generic name. Is this elementNumber? Unclear

2024-01-05 22:44 UTC, SukuWc commented on src/renderer/main/panels/configuration/components/Pages.svelte
>      try {
Please remove try..catch

2024-01-05 22:44 UTC, SukuWc commented on src/renderer/main/panels/profileCloud/ProfileCloud.svelte
@elsoazemelet

2024-01-07 16:39 UTC, elsoazemelet commented on src/renderer/main/panels/profileCloud/ProfileCloud.svelte
Changes are present on 'Fixed CR suggestions" (e67d4c1) commit.

2024-01-07 16:40 UTC, elsoazemelet commented on src/renderer/runtime/runtime.store.js
Definitely, testing is on going!

2024-01-08 09:47 UTC, SukuWc approved these changes

2024-01-08 15:43 UTC, merged